arb-dir: lib/l10n
template-arb-file: intl_en.arb
output-class: AppLocalizations
output-localization-file: app_localizations.dart
synthetic-package: true # make this false for package level localizations
output-dir: ./lib/l10n/generated